### ISSUE TITLE
希望加入可以配置文件系统路径的选项

### ISSUE THREAD

**Issue by zhuxindong** [KOHGYLW/KohgylwIFT#1]
我看到当前的文件系统是在webapp/KohgylwIFT/fileblocks目录下，但由于tomcat所在的盘可能并不是很大，所以希望加入可以配置的选项，用来指定文件系统的目录，以便于部署到其他磁盘

**Comment by KOHGYLW** [comment]
能让用户自行选择文件存储路径的功能其实一直在设计，不过由于项目结构上的一些限制目前尚未找到合理的实现方案。不过之后的升级中会加入此功能，尤其是在该项目使用SpringBoot重构后。
